# Generated by Django 4.2.3 on 2023-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('exercise_coordinator', models.CharField(max_length=200)),
                ('year', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
