# Generated by Django 4.2.3 on 2023-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='png_file',
            field=models.ImageField(default=1, upload_to='pngs/'),
            preserve_default=False,
        ),
    ]
