# Generated by Django 4.2.3 on 2023-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_baseexercise_alter_exercise_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='title',
            field=models.CharField(default='jkjk', max_length=200),
            preserve_default=False,
        ),
    ]
