# Generated by Django 4.2.3 on 2023-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_baseexercise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='solution',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
