# Generated by Django 4.2.3 on 2023-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_exercise_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
