# Generated by Django 4.2.5 on 2023-10-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_alter_exercise_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='topics',
            field=models.ManyToManyField(to='exercises.topic'),
        ),
    ]
