# Generated by Django 4.2.5 on 2023-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_topic_exercise_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='term',
            field=models.CharField(default=1999, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='university',
            field=models.CharField(default='TUM', max_length=200),
        ),
    ]
